version: '3.5'

services:
  web:
    env_file:
      - .env
    build:
      dockerfile: ./sample-apps/retry-middleware-app/Dockerfile
      context: ../../
    ports:
      - 8999:80
    volumes:
      - ./src:/app/src
