version: '3.5'

services:
    web:
        container_name: php-trello-integration-app-web
        env_file:
            - .env
        depends_on:
            - redis
        build:
            dockerfile: ./sample-apps/trello-integration-app/Dockerfile
            context: ../../
        ports:
            - 8999:80
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
        volumes:
            - ./src:/app/src
    redis:
        container_name: php-trello-integration-app-redis
        image: redis:latest
        volumes:
            - ./db/redis:/data
    ngrok:
        container_name: php-trello-integration-app-ngrok
        image: gtriggiano/ngrok-tunnel
        ports:
            - 4040:4040
        environment:
            TARGET_HOST: web
            TARGET_PORT: 80
        depends_on:
            - web