version: '3.5'

services:
    web:
        container_name: php-trello-app-web
        env_file:
            - .env
        depends_on:
            - redis
        build:
            dockerfile: ./sample-apps/trello-app/Dockerfile
            context: ../../
        ports:
            - 8999:80
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
        volumes:
            - ./src:/app/src
    redis:
        container_name: php-trello-app-redis
        image: redis:latest
        volumes:
            - ./db/redis:/data
