version: '3.5'

services:
  web:
    env_file:
      - .env
    depends_on:
      - redis
    build:
      dockerfile: ./sample-apps/rate-limit-app/Dockerfile
      context: ../../
    ports:
      - 8999:80
    volumes:
      - ./src:/app/src
      - ./vendor:/app/vendor
  redis:
    image: redis:latest
    volumes:
      - ./db/redis:/data
